### ISSUE TITLE
Cannot resolve host https://download.sculpin.io

### ISSUE THREAD

**Issue by peter279k** [sculpin/blog.sculpin.io#3]
As title, the sub domain seems to be unavailable.
Would you fix them? Thanks.

**Comment by simensen** [comment]
Hello!

Phar distribution (direct download) has been deprecated since last October. The host where download.sculpin.io lived was finally decommissioned.

Please see this article for more information:

https://blog.sculpin.io/2016/08/31/deprecating-phar-distribution-and-embedded-composer/

Apologies for the inconvenience. If you need anything else, or need help migrating, let us know!

/ping @dragonmantank

**Comment by peter279k** [comment]
Thank for @simensen  .
I think the ```README.md``` in this repo should be updated when publishing this post.
I see the ```If You Need Sculpin``` section has the wrong steps.

**Comment by simensen** [comment]
@peter279k fair enough. :)
